import os, sys, csv

# Periodically download the CSV file from:
#    https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/

fp = open( "WaveControlCompanyIDList.h", mode="w", encoding="utf-8" )
fp.write(
"""
// DO NOT EDIT!!! Generated by GenerateCompanyID.py from CompanyIdentfiers - CSV.csv!!!!
#pragma once

#include <map>
#include <string>

inline void WaveControl_InitialiseCompanyIDs( std::map<int, std::string>& CompanyID )
{
"""
);

first_row = False
with open( 'CompanyIdentfiers - CSV.csv', mode="r", encoding="utf-8" ) as csvfile:
    csvreader = csv.reader( csvfile )
    for row in csvreader:
        if first_row == False:
            first_row = True
            continue
        temp = row[2].replace("\"", "\\\"");
        fp.write( "    CompanyID[%s] = \"%s\";\n" % (row[0], temp) )

fp.write("\n}\n");